import "./globals.css";
import { Poppins } from "next/font/google";
import Tracker from "./track";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Penyewaan Motor | Rentalday",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo_rentalday.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" className={poppins.variable}>
      <body className="font-poppins antialiased">
        <Tracker />
        {children}
      </body>
    </html>
  );
}
